#!/bin/bash
# Auto-generated environment variables - %DATE%
export AWS_REGION=%AWS_REGION%
export PROJECT_PREFIX=%PROJECT_PREFIX%
export ENVIRONMENT=%ENVIRONMENT%
export GLUE_DATABASE_NAME=%PROJECT_PREFIX%_db
export RAW_BUCKET_NAME=%PROJECT_PREFIX%-raw-%ENVIRONMENT%
export CLEAN_BUCKET_NAME=%PROJECT_PREFIX%-clean-%ENVIRONMENT%
export ANALYTICS_BUCKET_NAME=%PROJECT_PREFIX%-analytics-%ENVIRONMENT%