AWSTemplateFormatVersion: '2010-09-09'
Description: 'Simplified AWS Data Lake Formation setup - uses service-linked role for easier deployment'

Parameters:
  ProjectPrefix:
    Type: String
    Default: dl-handson
    Description: Prefix for all resource names
    
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment type

  S3StackName:
    Type: String
    Description: Name of the S3 storage layer CloudFormation stack

  IAMStackName:
    Type: String
    Description: Name of the IAM roles CloudFormation stack

  GlueStackName:
    Type: String
    Description: Name of the Glue catalog CloudFormation stack

Resources:
  # NOTE: DataLakeDatabase is created by the Glue module, not here
  # We reference it via ImportValue to avoid resource conflicts

  # Register S3 Raw Data Location with service-linked role
  RawDataLocationResource:
    Type: AWS::LakeFormation::Resource
    Properties:
      ResourceArn: !Sub 
        - "${RawBucketArn}/*"
        - RawBucketArn: 
            Fn::ImportValue: !Sub "${S3StackName}-RawDataBucketArn"
      UseServiceLinkedRole: true

  # Register S3 Clean Data Location with service-linked role
  CleanDataLocationResource:
    Type: AWS::LakeFormation::Resource
    Properties:
      ResourceArn: !Sub 
        - "${CleanBucketArn}/*"
        - CleanBucketArn: 
            Fn::ImportValue: !Sub "${S3StackName}-CleanDataBucketArn"
      UseServiceLinkedRole: true

  # Register S3 Analytics Data Location with service-linked role
  AnalyticsDataLocationResource:
    Type: AWS::LakeFormation::Resource
    Properties:
      ResourceArn: !Sub 
        - "${AnalyticsBucketArn}/*"
        - AnalyticsBucketArn: 
            Fn::ImportValue: !Sub "${S3StackName}-AnalyticsDataBucketArn"
      UseServiceLinkedRole: true

  # NOTE: Crawlers are created by the Glue module, not here
  # We reference them via ImportValue to avoid resource conflicts

Outputs:
  DatabaseName:
    Description: Name of the Glue database (referenced from Glue stack)
    Value: 
      Fn::ImportValue: !Sub "${GlueStackName}-DatabaseName"
    Export:
      Name: !Sub "${AWS::StackName}-DatabaseName"

  RawDataCrawlerName:
    Description: Name of the raw data crawler (referenced from Glue stack)
    Value: 
      Fn::ImportValue: !Sub "${GlueStackName}-RawDataCrawlerName"
    Export:
      Name: !Sub "${AWS::StackName}-RawDataCrawlerName"

  CleanDataCrawlerName:
    Description: Name of the clean data crawler (referenced from Glue stack)
    Value: 
      Fn::ImportValue: !Sub "${GlueStackName}-CleanDataCrawlerName"
    Export:
      Name: !Sub "${AWS::StackName}-CleanDataCrawlerName"

  RawDataLocationResourceArn:
    Description: ARN of the registered raw data location
    Value: !Ref RawDataLocationResource
    Export:
      Name: !Sub "${AWS::StackName}-RawDataLocationArn"

  CleanDataLocationResourceArn:
    Description: ARN of the registered clean data location
    Value: !Ref CleanDataLocationResource
    Export:
      Name: !Sub "${AWS::StackName}-CleanDataLocationArn"

  AnalyticsDataLocationResourceArn:
    Description: ARN of the registered analytics data location
    Value: !Ref AnalyticsDataLocationResource
    Export:
      Name: !Sub "${AWS::StackName}-AnalyticsDataLocationArn"

  DataLakeSettingsStatus:
    Description: Lake Formation data lake settings configuration status
    Value: "Service-linked role configuration with S3 location registration"
    Export:
      Name: !Sub "${AWS::StackName}-DataLakeSettingsStatus"