AWSTemplateFormatVersion: '2010-09-09'
Description: 'Simplified AWS Data Lake Formation setup - uses service-linked role for easier deployment'

Parameters:
  ProjectPrefix:
    Type: String
    Default: dl-handson
    Description: Prefix for all resource names
    
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment type

  S3StackName:
    Type: String
    Description: Name of the S3 storage layer CloudFormation stack
    Default: datalake-s3-storage

  IAMStackName:
    Type: String
    Description: Name of the IAM roles CloudFormation stack
    Default: datalake-iam-roles

Resources:
  # Glue Database for Data Catalog
  DataLakeDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Sub "${ProjectPrefix}_db"
        Description: !Sub "Data Lake database for ${ProjectPrefix} project"
        Parameters:
          Environment: !Ref Environment
          Project: DataLake
          CreatedBy: CloudFormation

  # Register S3 Raw Data Location with service-linked role
  RawDataLocationResource:
    Type: AWS::LakeFormation::Resource
    Properties:
      ResourceArn: !Sub 
        - "${RawBucketArn}/*"
        - RawBucketArn: 
            Fn::ImportValue: !Sub "${S3StackName}-RawDataBucketArn"
      UseServiceLinkedRole: true

  # Register S3 Clean Data Location with service-linked role
  CleanDataLocationResource:
    Type: AWS::LakeFormation::Resource
    Properties:
      ResourceArn: !Sub 
        - "${CleanBucketArn}/*"
        - CleanBucketArn: 
            Fn::ImportValue: !Sub "${S3StackName}-CleanDataBucketArn"
      UseServiceLinkedRole: true

  # Register S3 Analytics Data Location with service-linked role
  AnalyticsDataLocationResource:
    Type: AWS::LakeFormation::Resource
    Properties:
      ResourceArn: !Sub 
        - "${AnalyticsBucketArn}/*"
        - AnalyticsBucketArn: 
            Fn::ImportValue: !Sub "${S3StackName}-AnalyticsDataBucketArn"
      UseServiceLinkedRole: true

  # Glue Crawler for Raw Data
  RawDataCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Sub "${ProjectPrefix}-raw-crawler"
      Role: !Sub 
        - "${GlueCrawlerRoleArn}"
        - GlueCrawlerRoleArn: 
            Fn::ImportValue: !Sub "${IAMStackName}-GlueCrawlerRoleArn"
      DatabaseName: !Ref DataLakeDatabase
      Description: "Crawler for raw data layer"
      Schedule:
        ScheduleExpression: "cron(0 1 * * ? *)"  # Daily at 1 AM UTC
      Targets:
        S3Targets:
          - Path: !Sub 
            - "s3://${RawBucketName}/ecommerce/"
            - RawBucketName: 
                Fn::ImportValue: !Sub "${S3StackName}-RawDataBucket"
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: LOG
      RecrawlPolicy:
        RecrawlBehavior: CRAWL_EVERYTHING
      Configuration: |
        {
          "Version": 1.0,
          "CrawlerOutput": {
            "Partitions": { "AddOrUpdateBehavior": "InheritFromTable" },
            "Tables": { "AddOrUpdateBehavior": "MergeNewColumns" }
          }
        }

  # Glue Crawler for Clean Data
  CleanDataCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Sub "${ProjectPrefix}-clean-crawler"
      Role: !Sub 
        - "${GlueCrawlerRoleArn}"
        - GlueCrawlerRoleArn: 
            Fn::ImportValue: !Sub "${IAMStackName}-GlueCrawlerRoleArn"
      DatabaseName: !Ref DataLakeDatabase
      Description: "Crawler for clean data layer"
      Schedule:
        ScheduleExpression: "cron(0 2 * * ? *)"  # Daily at 2 AM UTC
      Targets:
        S3Targets:
          - Path: !Sub 
            - "s3://${CleanBucketName}/"
            - CleanBucketName: 
                Fn::ImportValue: !Sub "${S3StackName}-CleanDataBucket"
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: LOG

Outputs:
  DatabaseName:
    Description: Name of the Glue database
    Value: !Ref DataLakeDatabase
    Export:
      Name: !Sub "${AWS::StackName}-DatabaseName"

  RawDataCrawlerName:
    Description: Name of the raw data crawler
    Value: !Ref RawDataCrawler
    Export:
      Name: !Sub "${AWS::StackName}-RawDataCrawlerName"

  CleanDataCrawlerName:
    Description: Name of the clean data crawler
    Value: !Ref CleanDataCrawler
    Export:
      Name: !Sub "${AWS::StackName}-CleanDataCrawlerName"

  DataLakeSettingsStatus:
    Description: Lake Formation data lake settings configuration status
    Value: "Simplified Configuration"
    Export:
      Name: !Sub "${AWS::StackName}-DataLakeSettingsStatus"